feat: 유저 정보 적재 기능 추가
fish-crew/fish-bun-backend pull request #11
Opened 2024-12-09 06:15 UTC by seungwonni

- 인증받은 유저 정보에 대해서 안전하게 유저 정보를 가져다가 활용 할 수 있도록 기능 추가
- 최상위 API -> /fish-bun/** 에서 인증을 받아야 접근 가능하도록 설정
- 인증 단계에서 유저 정보와, 유저 이력을 남기도록 기능 고도화
- BookController.java -> 요청값으로 사용자 정보를 가져오는 부분을 security 내부에서 가져오도록 기능 수정
- application-private.yml에 kakao Oauth 정보 추가

2024-12-09 12:09 UTC, hyebinnn requested changes
고생하셨어요 ㅎㅎ

2024-12-09 12:09 UTC, hyebinnn commented on src/main/java/fish/common/login/controller/KakaoLoginController.java
> +    public ModelAndView logout(@AuthenticationPrincipal AuthUserInfo userInfo) {
로그인 success 컨트롤러인 것 같은데 메서드 명이 logout으로 되어있습니다!

2024-12-09 12:09 UTC, hyebinnn commented on src/main/java/fish/common/user/entity/User.java
> +    private String provider; //타입 구분(kakao, google, naver)
필드 역할이 Type 구분을 위한거니까 명시적으로 providerType이라고 하면 어떨까욥??

2024-12-09 12:09 UTC, hyebinnn commented on src/main/java/fish/core/oauth/dto/KakaoUserInfo.java
> +    public String getProvider() {
만약 `providerType`으로 수정되면 요기도 메서드명도 수정되면 좋을거같아용

2024-12-09 12:09 UTC, hyebinnn commented on src/main/java/fish/core/oauth/dto/OAuth2UserInfo.java
> +    String getProvider();
요기도 ㅎㅎ

2024-12-09 12:09 UTC, hyebinnn commented on src/main/java/fish/core/oauth/service/OAuthUserService.java
> +    public OAuth2User loadUser(OAuth2UserRequest userRequest) {
이 부분 예외처리 제거해도 괜찮을까용??

2024-12-09 12:09 UTC, hyebinnn commented on src/main/resources/data.sql
> +insert into USER_BOOK (user_id, completed_flavor) values (5, '고구마 붕어빵');
사용자용 도감 user id가 통일되면 중복 데이터가 되기도하고 다양한 케이스로 넣으려고 일부러 다르게 해놨던건데 혹시 통일하신 이유가 있을까요?!

2024-12-10 00:38 UTC, seungwonni commented on src/main/java/fish/common/user/entity/User.java
> +    private String provider; //타입 구분(kakao, google, naver)
넵 수정해놓겠습니당~

2024-12-10 00:43 UTC, seungwonni commented on src/main/java/fish/common/login/controller/KakaoLoginController.java
> +    public ModelAndView logout(@AuthenticationPrincipal AuthUserInfo userInfo) {
앗 백엔드에서 임의로 테스트 용이라 서버 배포 후에 천천히 지워봐도 될까여??! ㅎㅎ

2024-12-10 00:43 UTC, seungwonni commented on src/main/resources/data.sql
> +insert into USER_BOOK (user_id, completed_flavor) values (5, '고구마 붕어빵');
ㅎㅎㅎ 테스트 용으로 잠깐 바꿨궁 변경 해뒀어용 추가적으로 스네이크 -> 카멜로 변경 해뒀어용

2024-12-10 04:23 UTC, hyebinnn approved these changes
GOOOOOOOOOD 😆

2024-12-10 04:23 UTC, merged