Feat: 붕어빵 등록 기능 추가
fish-crew/fish-bun-backend pull request #13
Opened 2024-12-11 16:08 UTC by seungwonni

- 파일 업로드 기능 추가
- ResponseUtil 개선(List 데이터 반환값이 없는 것에대한 처리)
- 붕어빵 등록 기능 추가

2024-12-11 17:53 UTC, hyebinnn requested changes
최고 최고

2024-12-11 17:53 UTC, hyebinnn commented on src/main/java/fish/core/util/FileUtils.java
> +        }
요기 주석 지워주기 > <
(사전에 서로 협의된 내용...)

2024-12-11 17:53 UTC, hyebinnn commented on src/main/java/fish/common/file/entity/FileEntity.java
> +    private String originFileName;     //사용자가 등록한
그냥.. 이건.. 개인적으로 신경이 좀 쓰여서...
'사용자가 등록한 파일 이름' 이라고 끝맺음 해주시면 안될까여? 🥺 (ㅋㅋㅋㅋ)

2024-12-12 04:03 UTC, seungwonni commented on src/main/java/fish/common/file/entity/FileEntity.java
> +    private String originFileName;     //사용자가 등록한
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 저도 같은 생각입니당 바로 수정하여 반영할게여

2024-12-12 04:03 UTC, seungwonni commented on src/main/java/fish/core/util/FileUtils.java
> +        }
넵ㅎㅎ 확인이요~

2024-12-12 04:15 UTC, merged